---
# samba role handlers

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart samba
  ansible.builtin.systemd:
    name: "{{ samba_systemd_unit }}"
    state: restarted
  when: samba_service_restart_enabled | default(true)
  listen: restart samba
