---
# samba role handlers

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart samba
  ansible.builtin.systemd:
    name: "{{ samba_systemd_unit }}"
    state: restarted
  when:
    - ansible_facts.services is defined
    - samba_systemd_unit in ansible_facts.services
    - samba_service_restart_enabled | default(true)
  listen: restart samba
