---
# Ansible collection requirements for Relay
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  
  - name: community.general
    version: ">=7.0.0"
  
  - name: containers.podman
    version: ">=1.10.0"
